# Site settings
title: 1
email: MarkBruns@MarkBruns.com
description: This is for 1) RockRapids.ART ... the others in this ecosystem of apps are 0) INFO 2) FUN, 3) GUIDE, 4) SHOP, 5) STORE, 6) WORK, 7) XYZ
twitter_username: MarkBruns
github_username:  RockRapids

# Build settings
markdown: kramdown
